CREATE TABLE categorie_produit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    libelle VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    actif BOOLEAN NOT NULL DEFAULT TRUE,
    niveau INT DEFAULT 1,
    categorie_parent_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (categorie_parent_id) REFERENCES categorie_produit(id)
);
