CREATE TABLE vente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference VARCHAR(50) NOT NULL UNIQUE,
    date_vente TIMESTAMP NOT NULL,
    total NUMERIC(38,2) NOT NULL,
    utilisateur_id BIGINT NOT NULL,
    statut VARCHAR(20) NOT NULL, -- EN_COURS / VALIDEE / ANNULEE
    created_at TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_vente_utilisateur
        FOREIGN KEY (utilisateur_id) REFERENCES utilisateur(id)
);
