CREATE TABLE stock_mouvement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- produit_id BIGINT NOT NULL,
    stock_id BIGINT NOT NULL,
    type_mouvement VARCHAR(20) NOT NULL, -- INITIAL / ENTREE / SORTIE / REAJUSTEMENT
    quantite INT NOT NULL CHECK (quantite > 0),
    date_mouvement TIMESTAMP NOT NULL,
    utilisateur_id BIGINT NOT NULL, -- utilisateur de l'entrepôt : caissier, gerant, administrateur
    commentaire VARCHAR(255),

    -- CONSTRAINT fk_stock_produit
        -- FOREIGN KEY (produit_id) REFERENCES produit(id),
    
    CONSTRAINT fk_stock_mouvement
        FOREIGN KEY (stock_id) REFERENCES stock(id),

    CONSTRAINT fk_stock_utilisateur
        FOREIGN KEY (utilisateur_id) REFERENCES utilisateur(id)
);
