CREATE TABLE vente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_vente VARCHAR(50) NOT NULL UNIQUE,
    date_vente TIMESTAMP NOT NULL,
    prix_total_ht NUMERIC(38,2) NOT NULL,
    utilisateur_id BIGINT NOT NULL,
    statut_vente VARCHAR(20) NOT NULL, -- pending / success / cancel
    created_at TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_vente_utilisateur
        FOREIGN KEY (utilisateur_id) REFERENCES utilisateur(id)
);
