CREATE TABLE vente_ligne (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vente_id BIGINT NOT NULL,
    produit_id BIGINT NOT NULL,
    quantite INT NOT NULL CHECK (quantite > 0),
    prix_unitaire NUMERIC(38,2) NOT NULL CHECK (quantite >= 0),

    CONSTRAINT fk_ligne_vente
        FOREIGN KEY (vente_id) REFERENCES vente(id),

    CONSTRAINT fk_ligne_produit
        FOREIGN KEY (produit_id) REFERENCES produit(id),

    CONSTRAINT uk_vente_produit UNIQUE (vente_id, produit_id)
);
-- Un produit une seule fois par vente